version: '3.5'
services:
  config-service:
    container_name: config-service
    build: config-service
    ports:
      - 8001:8001

  registry:
    container_name: registry
    restart: always
    build: registry
    ports:
      - 8761:8761
    depends_on:
      - config-service

  gateway:
    container_name: gateway
    restart: always
    build: gateway
    ports:
      - 8989:8989
    depends_on:
      - config-service
      - registry

  account-service:
    restart: on-failure
    container_name: account-service
    build: account-service
    ports:
      - 8081:8081
    depends_on:
      - config-service
      - registry
      - account_db

  bill-service:
    restart: on-failure
    container_name: bill-service
    build: bill-service
    ports:
      - 8082:8082
    depends_on:
      - config-service
      - registry
      - bill_db

  deposit-service:
    restart: on-failure
    container_name: deposit-service
    build: deposit-service
    ports:
      - 9999:9999
    depends_on:
      - config-service
      - registry
      - deposit_db

  notification-service:
    restart: on-failure
    container_name: notification-service
    build: notification-service
    depends_on:
      - config-service
      - registry
      - rabbitmq

  rabbitmq:
    container_name: payment-rabbitmq
    image: rabbitmq:3-management
    hostname: rabbitmq
    labels:
      NAME: "rabbitmq"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "123456789"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - 5673:5672
      - 15673:15672

  account_db:
    container_name: payment-account_db
    image: postgres:11.6
    restart: always
    shm_size: 1g
    environment:
      POSTGRES_USER: account
      POSTGRES_PASSWORD: account
      POSTGRES_DB: account
    volumes:
      - accountdata:/var/lib/postgresql/data
    ports:
      - "3306:5432"

  bill_db:
    container_name: payment-bill_db
    image: postgres:11.6
    restart: always
    shm_size: 1g
    environment:
      POSTGRES_USER: bill
      POSTGRES_PASSWORD: bill
      POSTGRES_DB: bill
    volumes:
      - billdata:/var/lib/postgresql/data
    ports:
      - "3307:5432"

  deposit_db:
    container_name: payment-deposit_db
    image: postgres:11.6
    restart: always
    shm_size: 1g
    environment:
      POSTGRES_USER: deposit
      POSTGRES_PASSWORD: deposit
      POSTGRES_DB: deposit
    volumes:
      - depositdata:/var/lib/postgresql/data
    ports:
      - "3308:5432"

#Volumes
volumes:
  accountdata:
    driver: local
  billdata:
    driver: local
  depositdata:
    driver: local